#!/usr/bin/env python

Import("env")



thirdparty_obj = []

thirdparty_sources = ["#thirdparty/libgl/raylib.h" , "#thirdparty/libgl/rcore.c"]

env_thirdparty = env.Clone()

env_thirdparty.add_source_files(thirdparty_obj, thirdparty_sources)

# Resources sources
scene_obj = []

env.add_source_files(scene_obj, "*.cpp")

# Append obj
env.Depends(scene_obj, thirdparty_obj)
