#!/usr/bin/env python

Import("env")


env.core_sources = []


# Add sources file 
env.add_source_files(env.core_sources, "*.cpp")

# Load SCsub files
SConscript('config/SCsub')
SConscript('debugger/SCsub')
SConscript('error/SCsub')
SConscript('extension/SCsub')
SConscript('object/SCsub')
SConscript('string/SCsub')
SConscript('templates/SCsub')
SConscript('input/SCsub')
SConscript('math/SCsub')
SConscript('io/SCsub')
SConscript('os/SCsub')


# Build it all as a library
lib = env.add_library("core", env.core_sources)
env.Prepend(LIBS=[lib])

# Append Lib
env.Depends(lib)
